from zeep import Client, Settings
from zeep.transports import Transport


settings = Settings(strict=False, xml_huge_tree=True)
client = Client('https://test103.officetrack.com/services/webservices.asmx?WSDL', settings=settings)

task_data ={
    'TaskNumber': 0,
    'EmployeeNumber': '2323',
    'StartDateTime': '202504050930',
    'DueDateTime': '202504051930',
    'Duration': 1080,
    'TaskTypeCode': 'SUP11',
    'Description': 'Criado via Zeep com sucesso - FAZENDO UPDATE',
    'Status': 'NewTask',
    'ExternalCreationDate': '202504050930',
    'Options': [],
    'WorkOrderNumber': None,
    'CustomerNumber': None,
    'DistributionAreaNumber': None,
    'TimeSlotReservationId': None,
    'VIN': None,
    'Notes': None,
    'Phone1': None,
    'Phone2': None,
    'ContractorCode': None,
    'ContactName': None,
    'CustomerName': None,
    'Categories': None,
    'Email': None,
    'Location': None,
    'GeocodeAddress': None,
    'Data1': 'Data1', 'Data2': None, 'Data3': None, 'Data4': None, 'Data5': None,
    'Data6': None, 'Data7': None, 'Data8': None, 'Data9': None, 'Data10': None,
    'Data11': None, 'Data12': None, 'Data13': None, 'Data14': None, 'Data15': None,
    'Data16': None, 'Data17': None, 'Data18': None, 'Data19': None, 'Data20': None,
    'Data21': None, 'Data22': None, 'Data23': None, 'Data24': None, 'Data25': None,
    'Data26': None, 'Data27': None, 'Data28': None, 'Data29': None, 'Data30': None,
    'Data31': None, 'Data32': None, 'Data33': None, 'Data34': None, 'Data35': None,
    'Data36': None, 'Data37': None, 'Data38': None, 'Data39': None, 'Data40': None,
    'CatalogItemNames': None,
    'CatalogCategory': None,
    'HiddenData1': None,
    'AdditionalInfoXml': None,
    'LimitCatalogCategoriesSelectionToCodes': None,
    'LimitCatalogItemsSelectionToCatalogNumbers': None,
    'MaximalRadiusForEntries': None,
    'ProhibitEntriesOutsideRadius': None,
    'UseQuantityOnlyCatalogItemEntryForm': None,
    'DoNotShowRefreshMessageInMobile': None,
    'SyncPoiCatalogItemsToTaskItems': None,
    'QuantityOnlyFormShowOnlyCatalogNumber': None,
    'TaskWithoutDates': None,
    'AllowSelectionOfPrivateCatalogItemsRegardlessOfTaskLimitations': None,
    'AggregateNumber': None,
    'OrderInAggregate': None,
    'Capacity1': None, 'Capacity2': None, 'Capacity3': None, 'Capacity4': None, 'Capacity5': None,
    'TimeWindows': None,
    'TimeWindowPriority': None,
    'ServiceTime': None,
    'JointServiceTime': None,
    'OrderInRoute': None, 
    'ExternalFiles': [],      
    'TaskItems': [],
    'Priority': None,
    'UpdateTaskItemsDefaultQuantity': None,
    'TaskCannotBeIncludedInBulkEntry': None,
    'AdditionalContractorCode': None,
    'TimeZone': None,
    'EmployeeNumberHasValue': True,
    'StartDateTimeHasValue': True,
    'DueDateTimeHasValue': True,
    'DurationHasValue': True,
    'TaskTypeCodeHasValue': True,
    'DescriptionHasValue': True,
    'ExternalCreationDateHasValue': True,
    'WorkOrderNumberHasValue': False,
    'CustomerNumberHasValue': False,
    'DistributionAreaNumberHasValue': False,
    'VinHasValue': False,
    'NotesHasValue': False,
    'Phone1HasValue': False,
    'Phone2HasValue': False,
    'ContractorCodeHasValue': False,
    'ContactNameHasValue': False,
    'CatalogItemNamesHasValue': False,
    'CatalogCategoryHasValue': False,
    'CustomerNameHasValue': False,
    'CategoriesHasValue': False,
    'EmailHasValue': False,
    'LocationHasValue': False,
    'GeocodeAddressHasValue': False,
    'Data1HasValue': True, 'Data2HasValue': False, 'Data3HasValue': False, 'Data4HasValue': False, 'Data5HasValue': False,
    'Data6HasValue': False, 'Data7HasValue': False, 'Data8HasValue': False, 'Data9HasValue': False, 'Data10HasValue': False,
    'Data11HasValue': False, 'Data12HasValue': False, 'Data13HasValue': False, 'Data14HasValue': False, 'Data15HasValue': False,
    'Data16HasValue': False, 'Data17HasValue': False, 'Data18HasValue': False, 'Data19HasValue': False, 'Data20HasValue': False,
    'Data21HasValue': False, 'Data22HasValue': False, 'Data23HasValue': False, 'Data24HasValue': False, 'Data25HasValue': False,
    'Data26HasValue': False, 'Data27HasValue': False, 'Data28HasValue': False, 'Data29HasValue': False, 'Data30HasValue': False,
    'Data31HasValue': False, 'Data32HasValue': False, 'Data33HasValue': False, 'Data34HasValue': False, 'Data35HasValue': False,
    'Data36HasValue': False, 'Data37HasValue': False, 'Data38HasValue': False, 'Data39HasValue': False, 'Data40HasValue': False,
    'HiddenData1HasValue': False,
    'AdditionalInfoXmlHasValue': False,
    'LimitCatalogCategoriesSelectionToCodesHasValue': False,
    'LimitCatalogItemsSelectionToCatalogNumbersHasValue': False,
    'MaximalRadiusForEntriesHasValue': False,
    'AggregateNumberHasValue': False,
    'OrderInAggregateHasValue': False,
    'Capacity1HasValue': False, 'Capacity2HasValue': False, 'Capacity3HasValue': False, 'Capacity4HasValue': False, 'Capacity5HasValue': False,
    'TimeWindowsHasValue': False,
    'TimeWindowPriorityHasValue': False,
    'ServiceTimeHasValue': False,
    'JointServiceTimeHasValue': False,
    'OrderInRouteHasValue': False,
    'ProhibitEntriesOutsideRadiusHasValue': False,
    'UseQuantityOnlyCatalogItemEntryFormHasValue': False,
    'DoNotShowRefreshMessageInMobileHasValue': False,
    'SyncPoiCatalogItemsToTaskItemsHasValue': False,
    'QuantityOnlyFormShowOnlyCatalogNumberHasValue': False,
    'TaskWithoutDatesHasValue': False,
    'AllowSelectionOfPrivateCatalogItemsRegardlessOfTaskLimitationsHasValue': False,
    'TimeSlotReservationIdHasValue': False,
    'ExternalFilesHasValue': False,
    'TaskItemsHasValue': False,
    'PriorityHasValue': False,
    'UpdateTaskItemsDefaultQuantityHasValue': False,
    'TaskCannotBeIncludedInBulkEntryHasValue': False,
    'AdditionalContractorCodeHasValue': False,
    'TimeZoneHasValue': False,
}

try:
    response = client.service.CreateOrUpdateTask(
        userName='3con4', 
        password='mV!5LcPrel5AeR!sn4Kki*babOS*o5', 
        operation='AutoSelect', 
        task=task_data)
    print(f"Resposta da API: {response}")
except Exception as e:
    print(f"Erro ao chamar a API: {e}")